## Description

This project provides a backend API for a question-answering system powered by Google AI's generative language model. Users can submit questions, receive answers generated by the AI model, and optionally store their questions and answers for future reference.

## Features

- **AI-powered question answering:** Leverages Google's Generative AI to provide comprehensive responses to user queries.
- **User authentication:** Implements JWT-based authentication for secure access to user-specific data.
- **Question storage (optional):** Users can choose to store their question-answer pairs for later retrieval.

## Prerequisites

- Node.js and npm (or yarn) installed on your system.
- A Google Cloud project with the Generative AI API enabled. You can follow Google's instructions for setting up Generative AI https://ai.google/(https://ai.google.dev/api/rest).

## Installation

1. Clone this repository:

   ```bash
   git clone [https://github.com/your-username/faiz-mohammad-answersai-backend.git](https://github.com/your-username/faiz-mohammad-answersai-backend.git)
